### ISSUE TITLE
Error deploying sample 2-structured-data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [modxevil/google-cloud-sdk#496]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

deploying project 2-structured-data (Getting started with Node.js):
gcloud preview app deploy app.yaml --promote

What is the expected output? What do you see instead?

ERROR: gcloud crashed (WindowsError): [Error 3] The system cannot find the path 
specified: 
'C:\\Users\\miguel\\AppData\\Local\\Google\\Cloud-SDK\\nodejs-getting-started\\2
-structured-data\\node_modules\\gcloud\\node_modules\\gce-images\\node_modules\\
google-auto-auth\\node_modules\\google-auth-library\\node_modules\\gtoken\\node_
modules\\google-p12-pem\\node_modules\\node-forge'

Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 369, in Run
    config_cleanup)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 204, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 278, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\./lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\./lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "C:\python27\lib\tarfile.py", line 2006, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "C:\python27\lib\tarfile.py", line 1878, in gettarinfo
    statres = os.lstat(name)
[output truncated]

```

Original issue reported on code.google.com by `mikeribe...@gmail.com` on 25 Jan 2016 at 4:29

**Comment by GoogleCodeExporter** [comment]
```
Greetings!  This looks like it may be caused by the maxpath limitation on 
Windows - this happens sometimes with NPM modules that have a lot of nested 
dependencies.  

One fix might be to install NPM 3, which flattens dependencies:

  npm install -g npm@3

Hopefully this fixes things up for you.  Let us know how it goes!
```

Original comment by `beckw...@google.com` on 25 Jan 2016 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
Thanks for yr prompt reply.

Installed npm3, same error.
Changed project location to c:\, and I was able to deploy.

Thanks again.
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=s
ig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=s
ig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
```

Original comment by `mikeribe...@gmail.com` on 26 Jan 2016 at 2:01

**Comment by GoogleCodeExporter** [comment]
```
Internal issue filed for the c:\ workaround. Thanks
```

Original comment by `gsfow...@google.com` on 27 Jan 2016 at 1:39
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Issue 527 has been merged into this issue.
```

Original comment by `z...@google.com` on 16 Feb 2016 at 11:11
